### ISSUE TITLE
No OTP is required when on Campus Network

### ISSUE THREAD

**Issue by proffapt** [siddsarkar/iitkgp-erp-auto-login-extension#13]
When connected to campus network there is no need for OTP.

Here's a possible solution:
- You can ping `iitkgp.ac.in` and if it doesn't drop packets, i.e. it is successful then it means the user is connected to campus network and just directly log him in bypassing the OTP requesting code.

Can use [this](https://github.com/proffapt/iitkgp-erp-login-pypi/blob/47450e336364358c75251a8ea4539d5c20fcd2da/src/iitkgp_erp_login/erp.py#L80-L99) as reference.

And btw, thanks for this amazing extension!!

**Comment by siddsarkar** [comment]
hey @proffapt really appreciate bringing this up!
I'll be pushing a fix to this soon

I'm glad you like this 🤗

P.S: would be helpful if you guys can contribute to this repo

**Comment by proffapt** [comment]
If I had time, you would have received the pr till now 🥲
This extension is one of the important things easing my workflow at KGP.

**Comment by proffapt** [comment]
Closing this issue, as discusses, will continue the legacy at https://github.com/metakgp/iitkgp-erp-auto-login. Thanks for this beautiful thing <3
