### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by ravisrc** [siddsarkar/iitkgp-erp-auto-login-extension#3]
#### It would be a great feature.

![image](https://user-images.githubusercontent.com/63353779/116180347-63d66680-a736-11eb-9996-257f7e7df9f1.png)

**Comment by siddsarkar** [comment]
In Firefox Android's recent update extensions support has been decreased. You can [read more here](https://blog.mozilla.org/addons/2021/01/20/extensions-in-firefox-for-android-update/).

But still you can use extensions on the [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en&gl=US) Version of Firefox. [Follow these article](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) to set it up.
